[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Helps pipe your output through an external pager"
documentation = "https://docs.rs/pager"
homepage = "https://gitlab.com/imp/pager-rs"
keywords = ["pager", "less", "more"]
license = "Apache-2.0/MIT"
name = "pager"
readme = "README.md"
repository = "https://gitlab.com/imp/pager-rs.git"
version = "0.12.1"

[badges]
travis-ci = { repository = "imp/pager-rs" }
gitlab = { repository = "imp/pager-rs" }

[dependencies]
errno = "0.2"
libc = "0.2"
